### ISSUE TITLE
Crash during --watch mode

### ISSUE THREAD

**Issue by xoxys** [webdeveric/webpack-assets-manifest#207] opened 2022-01-02 14:32 UTC
## The problem

Webpack crashes when I'm using the webpack-assets-manifest together with sass assets in `--watch` mode. Webpack starts fine and crashes after editing and saving a sass file.

## Technical details

```
webpack 5.65.0 compiled successfully in 71 ms


[webpack-cli] HookWebpackError: The "path" argument must be of type string. Received undefined
    at makeWebpackError (/home/user/Devel/private/hugo/hugo-geekdoc/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /home/user/Devel/private/hugo/hugo-geekdoc/node_modules/webpack/lib/Compilation.js:3055:12
    at eval (eval at create (/home/user/Devel/private/hugo/hugo-geekdoc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at fn (/home/user/Devel/private/hugo/hugo-geekdoc/node_modules/webpack/lib/Compilation.js:478:17)
    at _next3 (eval at create (/home/user/Devel/private/hugo/hugo-geekdoc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at eval (eval at create (/home/user/Devel/private/hugo/hugo-geekdoc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
-- inner error --
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.dirname (node:path:1276:5)
    at WebpackAssetsManifest.handleProcessAssetsAnalyse (/home/user/Devel/private/hugo/hugo-geekdoc/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:477:31)
    at fn (/home/user/Devel/private/hugo/hugo-geekdoc/node_modules/webpack/lib/Compilation.js:476:10)
    at _next3 (eval at create (/home/user/Devel/private/hugo/hugo-geekdoc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at eval (eval at create (/home/user/Devel/private/hugo/hugo-geekdoc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
caused by plugins in Compilation.hooks.processAssets
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Object.dirname (node:path:1276:5)
    at WebpackAssetsManifest.handleProcessAssetsAnalyse (/home/user/Devel/private/hugo/hugo-geekdoc/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:477:31)
    at fn (/home/user/Devel/private/hugo/hugo-geekdoc/node_modules/webpack/lib/Compilation.js:476:10)
    at _next3 (eval at create (/home/user/Devel/private/hugo/hugo-geekdoc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
    at eval (eval at create (/home/user/Devel/private/hugo/hugo-geekdoc/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

### Webpack version

`webpack 5.65.0`

### Webpack config

```
rules: [
      {
        test: /\.(sa|sc)ss$/,
        exclude: /node_modules/,
        type: "asset/resource",
        generator: {
          filename: "[name]-[contenthash:8].min.css"
        },
        use: [
          {
            loader: "postcss-loader",
            options: {
              postcssOptions: {
                plugins: ["autoprefixer"]
              }
            }
          },
          {
            loader: "sass-loader",
            options: {
              sassOptions: {
                outputStyle: "compressed"
              }
            }
          }
        ]
      }
    ]
```

**Comment by xoxys** [comment] 2022-01-03 20:09
The issue seems to be related to the webpack caching mechanism. Using `--watch --mode production` does not end up in the described crash, and using `cache: false` while running `--watch --mode development` works as well. If I enable caching again and run `--watch --mode development` it crashes again after saving a SCSS file.

**Comment by webdeveric** [comment] 2022-01-16 19:01
Duplicate of #182

**Closed by webdeveric** 2022-01-16 19:01 UTC
