### ISSUE TITLE
Deprecation warnings are thrown in Webpack v5

### ISSUE THREAD

**Issue by jasonwilliams** [webdeveric/webpack-assets-manifest#102] opened 2020-10-23 15:58 UTC
Webpack v5 is out and we updated, sadly we get some warnings being thrown.
They look like they're coming from this plugin.

`webpack-assets-manifest`: v3.1.1

```
(node:2251) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
    at WebpackAssetsManifest.handleEmit ([dir]/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:484:34)
    at Hook.eval [as callAsync] (eval at create ([dir]/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] ([dir]/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.emitAssets ([dir]/node_modules/webpack/lib/Compiler.js:739:19)
    at [dir]/node_modules/webpack/lib/Watching.js:80:21
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

**Comment by webdeveric** [comment] 2020-10-23 15:59
Duplicate of #95

**Closed by webdeveric** 2020-10-23 15:59 UTC

**Comment by jasonwilliams** [comment] 2020-10-23 16:12
@webdeveric maybe it makes sense to keep the issue (#95) open while it's still a problem? 
Otherwise you may get others raising the same issue again

**Comment by webdeveric** [comment] 2020-10-23 16:29
@jasonwilliams Good point :+1:
