### ISSUE TITLE
Building fails with Angular 14 (Webpack 5.72.1)

### ISSUE THREAD

**Issue by phipla** [webdeveric/webpack-assets-manifest#243] opened 2022-08-17 08:35 UTC
## The problem

Building fails with Angular 14

```
⠙ Generating browser application bundles (phase: setup).../Users/philippe/e-Cervo/src/cprocess2/webapps/node_modules/webpack/lib/NormalModule.js:227
			throw new TypeError(
			      ^

TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (/Users/philippe/e-Cervo/src/cprocess2/webapps/node_modules/webpack/lib/NormalModule.js:227:10)
    at WebpackAssetsManifest.handleCompilation (/Users/philippe/e-Cervo/src/cprocess2/webapps/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:784:18)
```

### Webpack version

5.72.1 (dependency for @angular-devkit#build-angular 14.1.2)

### Webpack config

```
const WebpackAssetsManifest = require('webpack-assets-manifest')

module.exports = {
    plugins: [new WebpackAssetsManifest({})],
}
```

### Operating system

MacOS Monterey (12.4)

**Comment by webdeveric** [comment] 2022-08-17 11:25
Possibly a duplicate of https://github.com/webdeveric/webpack-assets-manifest/issues/155 or https://github.com/webdeveric/webpack-assets-manifest/issues/122

Can you create a minimal reproducible example I can clone and run locally?

**Comment by phipla** [comment] 2022-08-17 13:16
Here you are https://github.com/phipla/test-webpack-assets-manifest

**Comment by webdeveric** [comment] 2022-08-17 13:49
@phipla The issue you're experiencing is due to package resolution. In the example repo, when you run `yarn why webpack`, it returns **two** different versions of webpack.

> yarn why webpack
   yarn why v1.22.15
   [1/4] Why do we have the module "webpack"...?
   [2/4] Initialising dependency graph...
   [3/4] Finding dependency...
   [4/4] Calculating file sizes...
   => Found "webpack@5.74.0"
   info Has been hoisted to "webpack"
   info Reasons this module exists
    - Hoisted from "@nrwl#angular#webpack"
    - Hoisted from "@nrwl#angular#@nrwl#cypress#webpack"
    - Hoisted from "@nrwl#angular#@nrwl#web#webpack"
   info Disk size without dependencies: "6MB"
   info Disk size with unique dependencies: "10.6MB"
   info Disk size with transitive dependencies: "26.17MB"
   info Number of shared dependencies: 53
   => Found "@angular-devkit/build-angular#webpack@5.73.0"
   info This module exists because "@angular-devkit#build-angular" depends on it.
   info Disk size without dependencies: "6.07MB"
   info Disk size with unique dependencies: "10.67MB"
   info Disk size with transitive dependencies: "26.24MB"
   info Number of shared dependencies: 53
   Done in 0.55s.

You can add this to your `package.json` to force only one version.

```json
 "resolutions": {
    "webpack": "5.73.0"
  }
```

**Closed by webdeveric** 2022-08-17 13:49 UTC

**Comment by phipla** [comment] 2022-08-17 14:50
Oh. I did look for multiple versions of webpack, but for some reason I missed it. Thanks and sorry !
