### ISSUE TITLE
[Feature Request] Include assets from copy-webpack-plugin in output

### ISSUE THREAD

**Issue by madflow** [webdeveric/webpack-assets-manifest#98] opened 2020-10-15 16:49 UTC
## The problem

In another Webpack Assets plugin - I can see assets copied by `copy-webpack-plugin` in the output.

For example I copy some TinyMce skins and the output yields:

```  "tinymce/skins/lightgray/content.mobile.min.css": "/dist/tinymce/skins/lightgray/content.mobile.min.css",```

With this plugin (which we currently use) - this does not seem to be possible.

Feature request:

* I want to be able to configure, if assets copied by  "copy-webpack-plugin" should be included in the output.
* The key should be the full relative path to the asset in the output directory

Thanks :+1: for the plugin.

### Webpack version

* 4.19.1

**Comment by webdeveric** [comment] 2020-10-15 17:18
Duplicate of #49

**Closed by webdeveric** 2020-10-15 17:18 UTC
